### ISSUE TITLE
YouTube URLs cause error: "Our systems have detected unusual traffic from your computer network"

### ISSUE THREAD

**Issue by daveyjones** [wrav/oembed#100]
Adding any YouTube URL results in the following error:

> Our systems have detected unusual traffic from your computer network. Please try your request again later. Why did this happen?
> IP address: 47.33.144.12
> Time: 2021-10-11T15:02:02Z
> URL: https://www.youtube.com/watch?v=yxT_GUSzbJE

And here's a screenshot:

<img width="741" alt="Screen Shot 2021-10-11 at 7 54 36 AM" src="https://user-images.githubusercontent.com/2852617/136811945-3985cef3-69ea-4be3-ad8d-0695fc49a8b0.png">

**Comment by andrewheins** [comment]
I just want to add a +1 here that our site suffered an outage today to this exact issue. There are two YouTube videos on our homepage, and it brought the whole page down. 

Is there a mechanism to include a YouTube API key with this plugin such that we could leverage the expanded API limits, and instead of getting shut down by 429s, instead just wind up paying for the API use?

This is kind of a critical bug. It doesn't just cause the YouTube embed to fail, but makes the entire page inoperable, and potentially knocks out the CMS side as well.
