### ISSUE TITLE
v3 does not return `.images` and other API data

### ISSUE THREAD

**Issue by maxfenton** [wrav/oembed#143]
After updating from v 2.3.0 to 3.0.0 (or 3.0.1) many of the expected API results like `entry.field.media.images` are completely missing.

![Screenshot 2023-11-20 at 3 38 11 PM](https://github.com/wrav/oembed/assets/906502/b1ed8e3d-ea7b-4bbb-8399-157af517bc21)

![Screenshot 2023-11-20 at 3 58 57 PM](https://github.com/wrav/oembed/assets/906502/d27f399c-4eec-42db-bb88-1a5fee5a793c)

**Comment by maxfenton** [comment]
This is a breaking change: https://github.com/wrav/oembed/commit/273ed21dc8961bb56478f3c4769d31da3c367244

**Comment by reganlawton** [comment]
@maxfenton  Thats why it was set to v3.0.0 a major release, normal used for breaking change or major changes.

The core package was completely upgraded to unblock other plugins that were needing `embed/embed` v4.

I do understand that some things may have changed but that is due to relying on the core package `embed/embed`.

I will update the doc in the README to reflect this but v2 of this plugin will still get bugfixes. New features will continue to v3+

**Comment by maxfenton** [comment]
@reganlawton Is there a plan to add `entry.field.media.images` and other existing API data to this plugin? We have code that relies on `entry.field.media.images` and then picks the largest image as a placeholder for videos.

**Comment by maxfenton** [comment]
Also, I _think_ Craft has a way to mark a plugin version as needing some specific change or approval. At the moment `craft update all` will go straight from 2.3.0 to 3.0.1 despite it being a major semver update.

**Comment by reganlawton** [comment]
@maxfenton I have updated with v3.0.2. The core package `embed/embed` seems to have changed a ton of keys and such and I'm using a ton of fallback mappings.

This is a fallback hack BUT if you have images with any particular URL and provider sites just let me know.

**Comment by maxfenton** [comment]
This is the output of `{% dd(subblock.video.media.images) %}` with 2.3.0:
![Screenshot 2023-12-04 at 9 22 26 AM](https://github.com/wrav/oembed/assets/906502/a736a6c9-16fe-442c-915a-67d309c08515)

And this is the output of `{% dd(subblock.video.media.images) %}` with 3.2.0:
![Screenshot 2023-12-04 at 9 29 27 AM](https://github.com/wrav/oembed/assets/906502/15daa5be-45be-4206-99d7-b459a2054914)

Is there any way in the CraftCMS plugin to set a mark for a breaking change that doesn't automatically update? `ddev craft update all` tries to update `oembed 2.3.0 => 3.0.3` despite the composer.json being specifically set to `^2.3.0`

**Comment by reganlawton** [comment]
@maxfenton This is because the image is the same just has a high res and standard res. This will be a `embed/embed` issue they choose, this why I've just given a fallback so code isn't breaking.

As for `ddev craft update all` I would personally never do that but that'd because I don't trust things lol but I looked up the docs, as I use a standard custom Dockerfile, but you can just use `ddev composer update` or `ddev composer update wrav/oembed`  this will not update your plugins major versions which IMHO is very bad that that is the case.

You will still have to set the composer.json to `"wrav/oembed": "2.*",` manually to revert BUT it shouldn't impact your site as there isn't any custom SQL used. That said always test in a DEV environment.

I'll still be fixing [v2.x-dev](https://packagist.org/packages/wrav/oembed#v2.x-dev) for bit longer but anything major feature wise will go to `v3` aka `master` branch
