### ISSUE TITLE
Serialization of 'class@anonymous' is not allowed

### ISSUE THREAD

**Issue by bartrylant** [wrav/oembed#81]
I rely heavily on the oembed plugin for showing YouTube video's on a website. However, since yesterday, I suddenly get:

```
Serialization of 'class@anonymous' is not allowed
Caused by: Embed\Exceptions\InvalidUrlException
Invalid url 'https://youtu.be/xxxx' (Status code 429)
in /home/xx/webapps/app-xxxxxx-live/vendor/embed/embed/src/Embed.php at line 142
```

This seems to go back to 

```
 in /home/ijnluser/webapps/app-xxx-live/vendor/wrav/oembed/src/services/OembedService.php at line 147 – yii\caching\xxx::set()

finally {
                if (Oembed::getInstance()->getSettings()->enableCache) {
                    Craft::$app->cache->set($cacheKey, $media, 'P1H');
                }
 
                return $media;
            }
```

Any ideas on what the problem might be here? The url's are correct. It's happening on my live site only, not on the local site.

**Comment by mijewe** [comment]
I'm having this issue too, and it's probably the same as https://github.com/wrav/oembed/issues/71 - have a look on there for workarounds

A [429 response](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) is Too Many Requests, and implies that you're being rate limited AFAIK.

**Comment by mijewe** [comment]
Been looking more into this, and though the root cause is potentially still the #71 issue, this still shouldn't happen as IMO there should be some response validation before it's saved to the cache.

That way even if `Embed::create()` returns this class@anonymous thing, it will still not cause this problem.

Something like this would be my layman's approach
```
if (property_exists($media, "code")) {
    Craft::$app->cache->set($cacheKey, $media, 'P1H');
}
```

**Comment by reganlawton** [comment]
I'll try assign sometime into this issue. Between recovery and going back to work fulltime been about gassed but I should be able to get some time.

**Comment by gglnx** [comment]
The problem was that this plugins creates an anonymous if Embed has failed, but anonymous classes can not be cached. In my pull request #84 I created an fallback adapter which handles this case. The fallback adapter can be cached.

An alternativ would be to return nothing, if something has failed. But this would be breaking change.
